[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
polars = { version = "0.29.0", features = ["csv", "lazy"] }
proptest = "1.1.0"
